language: perl
sudo: false
addons:
  apt:
    packages:
    - libssl-dev
perl:
  - "5.14"
  - "5.16"
  - "5.22"
branches:
  only:
    - master
install:
  - "source ./install-travis-dependencies.sh"
script: "dzil test"
