language: perl
sudo: false
addons:
  apt:
    packages:
    - libssl-dev
    - cpanminus
perl:
  - "5.14"
  - "5.24"
install:
  - "source ./install-travis-dependencies.sh"
  - "sudo cpanm MooseX::App@1.37"
script: "dzil test"
